### ISSUE TITLE
FpBinary objects can't be pickled.

### ISSUE THREAD

**Issue by baileyji** [smlgit/fpbinary#10]
Given the long creation time for large arrays and involved FP operations it would be nice to be able to cache arrays of FpBinary objects to disk. Presently any attempt to pickle results in: TypeError: can't pickle fpbinary.FpBinary objects

**Comment by smlgit** [comment]
https://github.com/smlgit/fpbinary/releases/tag/v1.3 .

Only pickle protocols including and above 2 are supported.
