### ISSUE TITLE
Would like to contact fpbinary contributors

### ISSUE THREAD

**Issue by cdboschen** [smlgit/fpbinary#24]
Hi! 
I am not sure if posting an issue to send this message is best practice (and if not I apologize). I would like to get in touch with the primary contributors for fpbinary. I have reviewed several options for implementing fixedpoint datatypes in Python and this one is by far my favorite. I am giving a presentation at the end of this month on implementing IIR/FIR filters in fixed point, demonstrated using this package. I would like to talk with you briefly about what I am doing and will be showing. I would be grateful if you could send me an email at boschen at loglin dot com. Thank you!

**Comment by smlgit** [comment]
Sorry, I have been very busy of late and couldn't get to your questions.

I can be contacted at smlgit@protonmail.com.
