### ISSUE TITLE
numpy float64 type causes kernel crash in fpBinarySwitchable

### ISSUE THREAD

**Issue by cdboschen** [smlgit/fpbinary#25]
The following results in a Dead kernel when executed in a Jupyter Notebook or the Spyder IDE (but appeared to work fine from a Python console directly).

```
import numpy as np
import fpbinary as fpb
fp_mode= False
test = np.float64(5)
node = fpb.FpBinarySwitchable(fp_mode=fp_mode, fp_value=fpb.FpBinary(4,0, True, test), float_value=test)
```

Sometimes there will be a delay, but subsequent cells in the notebook won't execute and eventually "Dead kernel" results. The solution is to use float(test) to ensure it is a standard float data type, but I am submitting this as fpBinarySwitchable would be more robust if it did this internally for its float parameter type. I am using the numpy float datatype as I am using the fpbinary library with numpy arrays which are set to float64 by default.

**Comment by smlgit** [comment]
Fixed at 879a414d997b38387262878867b945b9fe752d62.

Thanks to @cdboschen.
