### ISSUE TITLE
Error in doc for RoundingEnum?

### ISSUE THREAD

**Issue by cdboschen** [smlgit/fpbinary#26]
(Minor clerical error). The doc string for RoundingEnum describes Python as using 'near_zero' when converting floats to ints. I believe Python uses 'near_even' (as given by 'round()' as well as numpy 'np.round() ).

**Comment by smlgit** [comment]
Fixed at 8691f669dfbed5bc73b6bc01e0a798d17a4bda39.

Thanks to hawkeye @cdboschen.
