### ISSUE TITLE
Dead kernel when using resize method incorrectly

### ISSUE THREAD

**Issue by cdboschen** [smlgit/fpbinary#27]
Using the invalid condition of a the total bits being negative for the FpBinary.resize method results in a dead kernel:

```
# Creating a new FpBinary object properly creates a ValueError if integer_bits + fractional_bits is negative

# this will properly raise a ValueError exception
try:
    test = fpb.FpBinary(4, -5, value=12)
except ValueError:
    print("Nice Work!")

# this will crash the kernel (memory leak?)
test = fpb.FpBinary(4, 5, value=12)
test.resize((4,-5))
```

Tested using:

Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.33.0 -- An enhanced Interactive Python. Type '?' for help.

**Comment by smlgit** [comment]
Fixed at c425504f02b58c259e2f72441b3d1b4d7bd61e04.

Thanks to @cdboschen - nice catch.
