### ISSUE TITLE
Negative int_bits behavior is suspect

### ISSUE THREAD

**Issue by baileyji** [smlgit/fpbinary#6]
I'm trying to use this library to verify an FIR that has 16_15 signed samples with -10_26 signed coefficients (16 bit width, quantized by Xilinx's to 26 fractional bits as they are all quite small).

`x=FpBinary(int_bits=-10,frac_bits=26,signed=True) `

Takes a long time to execute and allows for values >1. Looking at the code it looks like the FpBinary constructor accepts signed values for int_bits but then fp small uses FP_UINT_TYPE for in_bits, so I'm guessing my request is being interpreted as for a VERY large integer part. the result of .format ((4294967287, 26)) seems to suggest this!

Is there a way for me to do this math with your library?

**Comment by smlgit** [comment]
Hi,

The int_bits parameter must be a natural number. It didn't even cross my mind to support the idea of negative int_bits. At present, you would need to scale your coefficients (and presumably your input data) to use the library.

Is this a feature you think is important?

**Comment by smlgit** [comment]
Ahhh! The more and more I think about it, the more obvious this was a pretty bad oversight. I apologize for the cock-up.

I'll look at a fix. How urgent is this for you?

**Comment by smlgit** [comment]
fa31172eeec4284bc25d873a6758dd36dae054af

FpBinary now supports negative int_bit values. A quick explanation of its use can be found in the help(FpBinary) documentation for the int_bit parameter.

The original design assumed int_bits would be >= 0 and unsigned ints were used to represent int_bits and frac_bits parameters. This was rectified and some other changes were required to support negative int_bits (str_ex() function needed some changes, the compare functionality for _FpBinarySmall was suspect when comparing two operands with large and non-similar bit formats and there were a few python object conversions that used the Unsigned versions of the functions).

**Comment by baileyji** [comment]
This was a perfect fix, thanks!
